Feature/update sampleapp
acesso-io/unicocheck-sample-swift pull request #1
Opened 2022-02-03 14:26 UTC by beatrizmonteiromendes

**Why?**
> We need to update the implementations to MAJOR 2.0.0 (facetec active liveness).

**Changes**
> Update the implementation and more.

**How to test**
> xcode

**Preview**
> n/a

Issues
> https://unicoidtech.atlassian.net/jira/software/c/projects/CM/boards/78?modal=detail&selectedIssue=CM-237

2022-02-03 14:38 UTC, MatheusDomingos commented on unicocheck-sample-swift/UnicoSampleView.swift
>      // MARK: IBActions
what about enter the `// MARK: IBActions` after the instructions

2022-02-03 14:43 UTC, MatheusDomingos requested changes

2022-02-03 14:43 UTC, MatheusDomingos commented on unicocheck-sample-swift/UnicoTheme.swift
> +        return nil
why not choose or specify the colors into this class? because there's no point having a class with all values nil.

2022-02-03 20:42 UTC, beatrizmonteiromendes commented on Podfile
> +pod ‘unicocheck-ios’, :git => 'https://github.com/acesso-io/unico-check-ios', :tag => '2.0.0'
done

2022-02-03 20:48 UTC, beatrizmonteiromendes commented on unicocheck-sample-swift/UnicoSampleView.swift
>      // MARK: IBActions
I move the instruction to the end of IBActions, check it out and see what do you think.

2022-02-03 20:52 UTC, beatrizmonteiromendes commented on unicocheck-sample-swift/UnicoTheme.swift
> +        return nil
I change 3 themes for give the example to the client

2022-02-04 13:02 UTC, MatheusDomingos approved these changes

2022-02-04 19:46 UTC, henrique-cocito approved these changes

2022-02-04 19:46 UTC, merged